---
title: "Benefits"
format: html
---

We believe the Tentsmuir Cycle Link is a vital piece of **community infrastructure** that will bring numerous benefits to North East Fife and beyond.

### 🌱 Connecting our Communities
The Tentsmuir Cycle Link will mean there is a continuous, safe and efficient cycle path from St Andrews to Dundee and beyond. This link between towns such as Tayport and Leuchars, will allow more access to local services without the need to rely on buses, bring more business to Tayport and Leuchars, make safe cycle commuting possible and generally enhance community connectivity in North East Fife.

#### - Providing our communities with options
The Tentsmuir Cycle Link will provide an alternative to car travel for many local journeys. This is especially important given the recent cuts to bus services in Tayport and Leuchars - althougn it won't replace these services it will provide options for the local community.

#### - Access to Leuchars Railway Station
It will be a 9km (25 - 45 mins) cycle along the cycle path from Tayport to Leuchars railway station. This will make it possible to commute by train to Edinburgh and beyond without the need for a car.

#### - More footfall in Tayport
The cycle path will bring more people into Tayport, especially from Leuchars and St Andrews. This will result in more business for local shops, cafes and pubs.

#### - Options to access Tentsmuir Forest and Beach
The Tentsmuir Cycle Link will provide a safe and efficient way for people to access Tentsmuir Forest and Beach by bike or on foot from Leuchars, Tayport and St Andrews. This will open up this beautiful area to more people without the need for a car.

### 🛡️ Safer for Everyone
Lots of folk are put off cycling by our pot holed and sometimes dangerous roads. Currently the options to cycle between St Andrews and Dundee or Tayport involve either a very busy and narrow road or taking a long detour via Tentsmuir on gravel track unsuitable for road bikes. The Tentsmuir Cycle link will provide a continuous, segregated, efficient link for cyclists avoiding busy roads meaning a safer journey for cyclists and less congestion and frustration for cars.

### 🏃 Boosts Health and Active Lifestyles
Cycle paths encourage more cycling and active travel boosting health. The Tentsmuir Cycle link will encourage community and open up cycling destinations via bike to far more people. It will be a beautiful route passing through forests and countryside and studies show that even just ten minutes in nature can greatly boost mental health and well being.

### 🌳 A **Biodiversity** Corridor
We plan on planting native hedges and wildflowers alongside the path encouraging insects, birds and other wildlife and creating a wildlife corridor between Leuchars and Tayport.

### 🌱 Cuts CO₂ Emissions
Cycle paths take cars off the road and studies have shown they can significantly reduce carbon emissions helping us reach a less carbon-intensive society.