---
title: "Survey"
format: html
---

We’re currently conducting a survey to gather feedback on the proposed Tentsmuir Cycle Path. Your input is crucial in designing a route that caters to both the community, commuters and visitors. 

We’ll submit the survey results to Fife Council as part of our campaign to secure their support and agreement to build the Tentsmuir Cycle Link.

The survey only takes five minutes and includes an opportunity to add any additional thoughts or ideas at the end. You can access via the link below 👇;

::: {style="text-align: center;"}
<a href="https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAANAAaabjBdUM1RBRkg3RzBBWjJVTEVZVEI4WEVaN1pTUy4u" role="button" data-toggle="tooltip" title="Please take our survey to help us move the cycle path forward" 
   style="background: radial-gradient(circle , #29962a, #507d2a); /* Gradient green */
          border: none;
          color: white;
          padding: 15px 32px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
          font-size: 18px;
          font-weight: bold;
          border-radius: 12px;
          width: 300px; /* Set a fixed width */" 
   target="survey"> <i class="fas fa-donate" style="margin-right: 8px;"></i>Complete the Survey Now</a>
:::

